[build-system]
requires = ["maturin>=1.0,<2.0"]
build-backend = "maturin"

[project]
name = "polars_candle"
requires-python = ">=3.8"
classifiers = [
  "Programming Language :: Rust",
  "Programming Language :: Python :: Implementation :: CPython",
  "Programming Language :: Python :: Implementation :: PyPy",
]


[dependencies]
polars = "*"


[dev-dependencies]
pytest = "*"
black = "*"
ruff = "*"
mypy = "*"
maturin = "*"
polars-distance = "*"